### ISSUE TITLE
Exception, Default-values for text-fields

### ISSUE THREAD

**Issue by r4fx** [hendrikreimers/TYPO3-content_designer#11]
contentdesigner doesn't work properly with MYSQL 5.6.x

Exceptions are thrown when you add a new page.

Exception
[1.1.12]: SQL error: 'Field 'tx_contentdesigner_flexform' doesn't have a default value' (pages:NEW12345)

**Comment by hendrikreimers** [comment]
Have you tried the current version?
There was a bugfix by another git user coming into the master branch and 
into the TER.

Am 10.10.2016 16:11, schrieb Rafał:
