### ISSUE TITLE
Problematic approach with TS in ext_tables

### ISSUE THREAD

**Issue by lolli42** [hendrikreimers/TYPO3-content_designer#13]
Hey, just stumbled upon this extension when I searched for usages of a specific core hook I plan to change.

Your solution to dynamically create content elements based on FE TypoScript is fragile and may break even in minor core version updates.

* Db calls and TS in ext_tables.php: Doing TypoScript initialization within ext_tables.php is an issue, starting with doing a DB call in ext_tables.php already: The core bootstrap is not ready, the scope is not clear, the core does some heavy caching in this area so anything dynamic will fail. It is also expensive to do so. This fires a full FE TypoScript in most BE requests. Doing TypoScript at this point in time may have additional unwanted side effects to the state of the system in further processing. For instance the FE TypoScript will now usually be fully loaded twice. This again may trigger quite some non-funny issues when it for instance comes to USER_INT parsing.

* Security considerations: Doing TS in ext_tables means the called id is not yet sanitized, the core determination and checking of routing options and id is not done, yet. This should really be checked twice.

* Install tool: Helper method "isModuleAcceptable". The install tool tells you that the ext_tables.php file is not clean and reports the extension as broken. The extensions solution is a hack to disable itself if run within install tool context ...

The main point is that stuffing this sort of magic into ext_tables is a problematic approach.

The extension will probably suffer from various side effects that are rather hard to track down, it will be performance wise expensive, caching is difficult, it may spoil other core internal cache mechanisms, and the approach may break easily with core upgrades. ext_tables is just not meant to be used that way.

If this is kept, extension authors should prepare for maintenance efforts mid-term to keep that solution alive.

**Comment by hendrikreimers** [comment]
Dear Christian,

thank you for your Feedback. You're right and i know it!

This extension becomes old and based on old versions and variants in a time before Fluid/Extbase etc.
Currently i'm working/testing new ways without breaking into the Core so much, but keeping the user experience to fast and easy create content elements without learning new ways (or reading a huge manual).

If you, or someone else, would like to support me, I would be very happy about it.

Cheers!
Hendrik

**Comment by lolli42** [comment]
There are various solutions to kick start content elements relatively easily.
Maybe have a look at ext: mask for instance.

**Comment by hendrikreimers** [comment]
Yeah you're right! Mask is very interesting...
My Ext grows over the time and started before Mask or DCE exists. Many users like it already. That's why i'm not stopped developing. That's why i rethink the methods and features (by the same issues you've started you're comments) and also i think about, whether to stop development and concentrate to other projects too.

Thank you for you're great feedback. It is very helpfull!
